using System.Diagnostics;

internal class EulerProject45
{ 
    static readonly string question = "Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:\r\n\r\n" +
                                      "\tTriangle   \tTn = n(n + 1)/2\t \t1,3,6,10,15,...\r\n" +
                                      "\tPentagonal \tPn = n(3n − 1)/2  \t1,5,12,22,35,...\r\n" +
                                      "\tHexagonal  \tHn = n(2n − 1)\t  \t1,6,15,28,45,...\r\n\r\n" + 
                                      "It can be verified that T285 = P165 = H143 = 40755.\r\n\r\n" + 
                                      "Find the next triangle number that is also pentagonal and hexagonal.";
    static readonly string separator = new string('-', 50) + "\r\n";


    static void Main()
    {
        Console.WriteLine(question);
        Console.WriteLine(separator);
        Stopwatch sw = Stopwatch.StartNew();

        ulong result = Solution.Solve();

        sw.Stop();
        Console.WriteLine("Elapsed: " + sw.ElapsedMilliseconds + "ms");
        Console.WriteLine("Result: " + result);
        Console.ReadLine();
    }

    private static class Solution
    {
        internal static ulong Solve()
        {
            ulong n = 286;
            ulong t = GetTriangleNumber(n);

            HashSet<ulong> pentagonalNumbers = new HashSet<ulong>();
            HashSet<ulong> hexagonalNumbers = new HashSet<ulong>();

            for (ulong i = 1; i <= 1500000; i++)
            {
                pentagonalNumbers.Add(GetPentagonalNumber(i));
                hexagonalNumbers.Add(GetHexagonalNumber(i));
            }

            while (!(pentagonalNumbers.Contains(t) && hexagonalNumbers.Contains(t)))
                t = GetTriangleNumber(++n);

            return t;
        }

        private static ulong GetTriangleNumber(ulong n) => n * (n + 1) / 2;
        
        private static ulong GetPentagonalNumber(ulong n) => n * (3 * n - 1) / 2;

        private static ulong GetHexagonalNumber(ulong n) => n * (2 * n - 1);
    }
}

