using System.Diagnostics;
using System.Numerics;

internal class EulerProject44
{
    static readonly string question = "Pentagonal numbers are generated by the formula, P_n = n(3n - 1)/2. The first ten pentagonal numbers are:\r\n\r\n" + 
                                      "\t1,5,12,22,35,51,70,92,117,145,...\r\n\r\n" + 
                                      "It can be seen that P_4 + P_7 = 22 + 70 = 92 = P_8. However, their difference, 70 - 22 = 48, is not pentagonal.\r\n\r\n" + 
                                      "Find the pair of pentagonal numbers, P_j and P_k, for which their sum and difference are pentagonal \r\n" + 
                                      "and D = |P_k - P_j| is minimised; what is the value of D?";
    static readonly string separator = new string('-', 50) + "\r\n";


    static void Main()
    {
        Console.WriteLine(question);
        Console.WriteLine(separator);
        Stopwatch sw = Stopwatch.StartNew();

        BigInteger result = Solution.Solve();

        sw.Stop();
        Console.WriteLine("Elapsed: " + sw.ElapsedMilliseconds + "ms");
        Console.WriteLine("Result: " + result);
        Console.ReadLine();
    }

    private static class Solution
    {
        internal static BigInteger Solve()
        {
            PentagonalNumber pentagonalNumber = new PentagonalNumber();
            BigInteger[] pentNums = new BigInteger[10000];
            BigInteger minD = 999999999999;

            for (int i = 0; i < 10000; i++)
                pentNums[i] = pentagonalNumber.Next();

            HashSet<BigInteger> d = new HashSet<BigInteger>(pentNums);

            for (int i = 0; i < pentNums.Length - 1; i++)
            {
                for (int j = i + 1; j < pentNums.Length; j++)
                {
                    BigInteger sum = pentNums[i] + pentNums[j];
                    BigInteger dif = pentNums[j] - pentNums[i];
                    if (d.Contains(sum) && d.Contains(dif))
                        minD = BigInteger.Min(minD, dif);
                }
            }
            return minD;
        }

        private class PentagonalNumber
        {
            // P_n = n(3n - 1)/2
            int n;

            public PentagonalNumber() => n = 0;

            public PentagonalNumber(int _n) => n = _n;

            public void Set(int _n) => n = _n;

            public void Reset() => n = 0;

            private BigInteger GetPentagonalNumber() => n * (3 * n - 1) / 2;
            
            public BigInteger Next()
            {
                n++;
                return GetPentagonalNumber();
            }

            public BigInteger Previous()
            {
                n--;
                return GetPentagonalNumber();
            }
        }
    }
}

